import Header from './components/Header'
import './globals.css'
import { Barlow, Montserrat, Outfit, Raleway } from 'next/font/google'

const font = Outfit({ subsets: ['latin'],weight:["100","200","400","500","600","700","800"] })

export const metadata = {
  title: 'LinkSpot',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        {children}
        </body>
    </html>
  )
}
